modLoader="javafml" 
loaderVersion="[40,)" 
license="MIT"

[[mods]] 
modId="lifeofnexus" 
version="${file.jarVersion}" 
displayName="LifeOfNexus" 
logoFile="lifeofnexus.png" 
credits="Thanks for this example mod goes to Akhil" 
authors="NexusDino" 
description='''
    The life of me in minecraft. Just insane mod
'''
[[dependencies.lifeofnexus]] 
    modId="forge" 
    mandatory=true
    versionRange="[40,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.lifeofnexus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
